### ISSUE TITLE
Values generated by XSInstance.generate() for xsd decimal type is not valid

### ISSUE THREAD

**Issue by GoogleCodeExporter** [santhosh-tekuri/jlibs#42]
```
What steps will reproduce the problem?
  Generate xml by XSInstance.generate() for xsd with decimal type

What is the expected output? What do you see instead?
  Generated values like "1234.456E123", but "E" is not allowed (http://books.xmlschemata.org/relaxng/ch19-77057.html)

What version of the product are you using? On what operating system?
  r1753, Windows

Please provide any additional information below.
  http://www.w3.org/TR/xmlschema-2/#decimal
  I believe only xsd float type allows exponent notation. IBM Websphere fails on validate decimal with exponent. 

```

Original issue reported on code.google.com by `kolobo...@gmail.com` on 26 Nov 2013 at 1:54

**Comment by IsraSmida** [comment]
I have the same problem and i'm using the jlibs-2.0.

`ERROR : cvc-datatype-valid.1.2.1: '1.2861521230781933E308' is not a valid value for 'decimal'.`

**Comment by santhosh-tekuri** [comment]
try with jlibs-xsd 2.2.1

**Comment by IsraSmida** [comment]
Sorry but even with 2.2.1 i'm having the same problem.

**Comment by IsraSmida** [comment]
I'm generating and validating the XML documents from the same xsd document : 

`<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Quote" type="QuoteType" />
	<xs:element name="Order" type="OrderType" />
	<xs:complexType name="QuoteType">
		<xs:sequence>
			<xs:element name="Line" type="ProdType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderType">
		<xs:sequence>
			<xs:element name="Line" type="OrderLineType" maxOccurs=" unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProdType">
		<xs:sequence>
			<xs:element name="Desc" type="xs:string" />
			<xs:element name="Price" type="xs:decimal" />
			<xs:any minOccurs="0" maxOccurs="unbounded"/> 
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderLineType">
		<xs:sequence>
			<xs:element name="Product" type="ProdType" />
			<xs:element name="Qty" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>
`

**Comment by santhosh-tekuri** [comment]
fixed with commit c782f75c33c25d7f234029dd22a30d876c3db1d4

**Comment by IsraSmida** [comment]
There is no more "E" in the decimal values generated. But the genereated values still not valid because there is a "," instead of ".".

The XSD file : 

`<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Quote" type="QuoteType" />
	<xs:element name="Order" type="OrderType" />
	<xs:complexType name="QuoteType">
		<xs:sequence>
			<xs:element name="Line" type="ProdType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderType">
		<xs:sequence>
			<xs:element name="Line" type="OrderLineType" maxOccurs=" unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProdType">
		<xs:sequence>
			<xs:element name="Desc" type="xs:string" />
			<xs:element name="Price" type="xs:decimal" />
			<xs:any minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderLineType">
		<xs:sequence>
			<xs:element name="Product" type="ProdType" />
			<xs:element name="Qty" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema> `

The XML generated :

`<?xml version="1.0" encoding="UTF-8"?>

<Order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   
   <Line>
      
      <Product>
         <Desc>Desc1</Desc>
         <Price>700,276</Price>
      </Product>
      <Qty>-1977436097</Qty>
   </Line>
   
   <Line>
      
      <Product>
         <Desc>Desc2</Desc>
         <Price>142,445</Price>
      </Product>
      <Qty>-615530219</Qty>
   </Line>
</Order>`

**Comment by santhosh-tekuri** [comment]
for me it is working fine. Looks like your system locale uses comma for dot.

http://stackoverflow.com/questions/8601011/string-format-uses-comma-instead-of-point

can you tell me what is your system locale

**Comment by santhosh-tekuri** [comment]
fixed with commit b16304082784196270b09e93806aab6302b66600

**Comment by IsraSmida** [comment]
Now it works thank you !

**Comment by james319** [comment]
Hi @santhosh-tekuri , is there a new maven version with this fix? (remove scientific notation "E" )
Currently I see <version>2.2.1</version> but the fix is not included.
