### ISSUE TITLE
Repo on Maven Central

### ISSUE THREAD

**Issue by GoogleCodeExporter** [santhosh-tekuri/jlibs#52]
```
Is there any chance this library could be hosted on Maven Central?  It's 
extremely useful but some of my fellow devs are scared when they see 'dropbox' 
in my pom :)

```

Original issue reported on code.google.com by `shmish...@gmail.com` on 18 Jun 2014 at 8:16

**Comment by wakingrufus** [comment]
I saw at https://issues.sonatype.org/browse/OSSRH-10355 that your upload has been approved on sonatype, but it looks like you have not actually published there.  Any update on this?

**Comment by santhosh-tekuri** [comment]
they are now available in maven central:
http://mvnrepository.com/artifact/in.jlibs
