### ISSUE TITLE
Custom XML Crawler listeners lead to issues on Windows-based systems

### ISSUE THREAD

**Issue by bugflux** [santhosh-tekuri/jlibs#55]
I made a custom WSDL "dumper" using your XMLCrawler. It differs from your default in that the files are stored locally with the same structure as the remote ones (except for cross-domain issues).

https://github.com/bugflux/wsdl-dump/blob/master/src/main/java/com/andreprata/wsdldump/WsdlDump.java

It works just fine in OS X, but then I had to run it on Windows and I noticed that your library will modify the XML "hrefs" to paths with backslashes. These cannot be parsed using XJC, it is expecting forward slashes everywhere, even for Windows systems.

**Comment by santhosh-tekuri** [comment]
do you have any such wsdl url, to test it

**Comment by santhosh-tekuri** [comment]
no response from reporter. closing...
