### ISSUE TITLE
Generate XML using defined namespace prefixes 

### ISSUE THREAD

**Issue by brendonstephens93** [santhosh-tekuri/jlibs#58]
Feature Request: Generate the sample XML using the namespace prefixes defined in the xsd files.

**Comment by santhosh-tekuri** [comment]
Yes. this makes the generated sample more readable...
Xerces xsd parser, does not give any prefix information. need to manually parse xsd files to get namespace prefixes.

**Comment by santhosh-tekuri** [comment]
you have to do the following to use the sample prefixes in generates sample xml:

```java
String xsdFile = ...
XSModel xsModel = ...
XMLDocument xml = ....
XSUtil.suggestNamespacePrefixes(URLUtil.toURL(xsdFile), xml);
new XSInstance().generate(...)
```

**Comment by brendonstephens93** [comment]
Perfect! Thanks a million!

**Comment by brendonstephens93** [comment]
Hi Santhosh.

This is my first time using GitHub, I am not quite sure how it works. I can see you have made the changes but my Maven can't seem to pick them up. I can only see version 2.1 not version 2.2 in Maven. 

See: http://search.maven.org/#search%7Cga%7C1%7Cjlibs

Thanks for your help!

**Comment by santhosh-tekuri** [comment]
It is not recommended to increase version number for each change. only on release it will be available in Maven central repo. you have to use snapshot versions to get this change:

```xml
<project>

<dependencies>
    <dependency>
        <groupId>in.jlibs</groupId>
        <artifactId>jlibs-xsd</artifactId>
        <version>2.2-SNAPSHOT</version>
    </dependency>
</dependencies>
<repositories>
    <repository>
      <id>sonatype-snapshots</id>
      <name>sonatype snapshots repository</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
  </repositories>
</project>
```

use 2.2-SNAPSHOT as shown above. Do not forget to add repository to your pom. 
after above changes, your build should pick up the changes
