### ISSUE TITLE
Local namespace prefix not being output in XSInstance

### ISSUE THREAD

**Issue by brendonstephens93** [santhosh-tekuri/jlibs#59]
There seems to be a problem with outputting the local namespace prefix in the sample XML files. If the xsd contains elementFormDefault="qualified" then no local namespaces will be output. However if I change to elementFormDefault="unqualified" the root local namespace will be output, but the others will not.

Perhaps it is the way I am generating the sample xml? Below is my code:

##### getSampleXmlString(File xsdFile, String xsdRoot)

		XSModel xsModel = new XSParser().parse(xsdFile.getAbsolutePath());

		XSInstance xsInstance = new XSInstance();
		xsInstance.generateAllChoices = true;
		xsInstance.minimumElementsGenerated = 1;
		xsInstance.maximumElementsGenerated = 1;

		// make a (probably incorrect) assumption that item(0) is always the root namespace
		QName rootElement = new QName(xsModel.getNamespaces().item(0), xsdRoot);

		StringWriter sampleXml = new StringWriter();

		XMLDocument xml = new XMLDocument(new StreamResult(sampleXml), false, 4, null);
		
		// suggest namespace prefixes so they don't default to ns1, ns2 etc
		XSUtil.suggestNamespacePrefixes(URLUtil.toURL(xsdFile.getAbsolutePath()), xml);
		
		xsInstance.generate(xsModel, rootElement, xml);

**Comment by santhosh-tekuri** [comment]
I did not get what is the issue;
if the schema is:

```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           elementFormDefault="qualified">
    <xsd:element name="Author">
        <xsd:complexType>
          <xsd:sequence>
             <xsd:element name="name" type="xsd:string"/>
             <xsd:element name="phone" type="xsd:string"/>
          </xsd:sequence>
          <xsd:attribute name="id" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
```

the generated sample is:

```xml
<!--@(id?) (name , phone)-->
<Author xmlns="http://www.w3schools.com" id="id1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>name1</name>
    <phone>phone1</phone>
</Author>
```
if i change `elementFromDefault` to `unqualified` in schema, the generated sample is:

```xml
<!--@(id?) (name , phone)-->
<ns:Author xmlns:ns="http://www.w3schools.com" id="id1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>name1</name>
    <phone>phone1</phone>
</ns:Author>
```

can you explain what is the problem in above generated samples?

**Comment by brendonstephens93** [comment]
#### Example Input
```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.w3schools.com" xmlns:w3c="http://www.w3schools.com"
  elementFormDefault="unqualified">
  <xsd:element name="Author">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string"/>
        <xsd:element name="phone" type="xsd:string"/>
        <xsd:element name="Address" type="w3c:addressType"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="addressType">
    <xsd:sequence>
      <xsd:element name="addressLine1" type="xsd:string"/>
      <xsd:element name="addressLine2" type="xsd:string"/>
      <xsd:element name="country" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
```

#### Generated Output
```
<?xml version="1.0" encoding="UTF-8"?>
<!--@(id?) (name , phone , Address)-->
<w3c:Author xmlns:w3c="http://www.w3schools.com" id="id1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>name1</name>
    <phone>phone1</phone>
    <Address>
        <addressLine1>addressLine11</addressLine1>
        <addressLine2>addressLine21</addressLine2>
        <country>country1</country>
    </Address>
</w3c:Author>
```

#### Expected Output
````
<?xml version="1.0" encoding="UTF-8"?>
<!--@(id?) (name , phone , Address)-->
<w3c:Author xmlns:w3c="http://www.w3schools.com" id="id1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <w3c:name>name1</w3c:name>
    <w3c:phone>phone1</w3c:phone>
    <w3c:Address>
        <w3c:addressLine1>addressLine11</w3c:addressLine1>
        <w3c:addressLine2>addressLine21</w3c:addressLine2>
        <w3c:country>country1</w3c:country>
    </w3c:Address>
</w3c:Author>
````

When generating the sample XML using oXygen, I am able to achieve the expected output both when elementFormDefault="unqualified" and  elementFormDefault="qualified".

**Comment by santhosh-tekuri** [comment]
the expected xml is not valid as per the schema. it seems oxygen editor has bug.

if you are using linux, you can do following to verify this:

```
$ xmllint --schema schema.xsd expected.xml                                                                                                            <?xml version="1.0" encoding="UTF-8"?>
<!--@(id?) (name , phone , Address)-->
<w3c:Author xmlns:w3c="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="id1">
    <w3c:name>name1</w3c:name>
    <w3c:phone>phone1</w3c:phone>
    <w3c:Address>
        <w3c:addressLine1>addressLine11</w3c:addressLine1>
        <w3c:addressLine2>addressLine21</w3c:addressLine2>
        <w3c:country>country1</w3c:country>
    </w3c:Address>
</w3c:Author>
expected.xml:4: element name: Schemas validity error : Element '{http://www.w3schools.com}name': This element is not expected. Expected is ( name ).
expected.xml fails to validate
```

where as the generated sample xml by jlibs validates perfectly:

```
$ xmllint --schema schema.xsd generated.xml                                                                                                           <?xml version="1.0" encoding="UTF-8"?>
<!--@(id?) (name , phone , Address)-->
<w3c:Author xmlns:w3c="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="id1">
    <name>name1</name>
    <phone>phone1</phone>
    <Address>
        <addressLine1>addressLine11</addressLine1>
        <addressLine2>addressLine21</addressLine2>
        <country>country1</country>
    </Address>
</w3c:Author>
generated.xml validates
```

**Comment by brendonstephens93** [comment]
Sorry you are right the expected output I posted above does not validate against the schema. If I change to elementFormDefault="qualified", the expected output validates now however jlibs will not generated with any local namespace. Validation passes below using Oxygen and this website: http://www.freeformatter.com/xml-validator-xsd.html

#### Example Input
````
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.w3schools.com" xmlns:w3c="http://www.w3schools.com"
  elementFormDefault="qualified">
  <xsd:element name="Author">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string"/>
        <xsd:element name="phone" type="xsd:string"/>
        <xsd:element name="Address" type="w3c:addressType"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="addressType">
    <xsd:sequence>
      <xsd:element name="addressLine1" type="xsd:string"/>
      <xsd:element name="addressLine2" type="xsd:string"/>
      <xsd:element name="country" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
````

#### Generated Output
````
<?xml version="1.0" encoding="UTF-8"?>
<!--@(id?) (name , phone , Address)-->
<Author xmlns="http://www.w3schools.com" id="id1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>name1</name>
    <phone>phone1</phone>
    <Address>
        <addressLine1>addressLine11</addressLine1>
        <addressLine2>addressLine21</addressLine2>
        <country>country1</country>
    </Address>
</Author>
````

#### Expected Output (can be generated by and validated by Oxygen)
````
<?xml version="1.0" encoding="UTF-8"?>
<w3c:Author xmlns:w3c="http://www.w3schools.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.w3schools.com file:/C:/Apps/Java/Workspaces/battmap1/battmap/xsd/sample.xsd" id="">
    <w3c:name></w3c:name>
    <w3c:phone></w3c:phone>
    <w3c:Address>
        <w3c:addressLine1></w3c:addressLine1>
        <w3c:addressLine2></w3c:addressLine2>
        <w3c:country></w3c:country>
    </w3c:Address>
</w3c:Author>
````

**Comment by santhosh-tekuri** [comment]
both generated output and expected output are logically same.  
jlibs used empty prefix for namespace "http://www.w3schools.com"  
where as oxygen used w3c prefix for namespace "http://www.w3schools.com"  

you can verify that jlibs generated output validates with the xsd using http://www.freeformatter.com/xml-validator-xsd.html

**Comment by brendonstephens93** [comment]
Yes both are valid, but when generating the elementFormDefault="qualified" shouldn't the prefix be displayed for each element? See http://stackoverflow.com/a/23453115/4200631 for a better explanation.

**Comment by santhosh-tekuri** [comment]
`elementFromDefault="qualified"` means the local elements in schema must be qualified with schema's targetNamespace.

in your schema, local elements are name, phone, Address, addressLine1, addressLine2 and country.
these elements must be quailified with namespace `http://w3schools.com`

if you see the generated xml, all those above elements have no prefix means empty prefix. and 
`xmlns="http://w3schools.com"` binds empty prefix to `http://w3schools.com`. thus all these elements are qualified with namespace `http://w3schools.com` 

it does not matter what prefix is. what is important is to which namespace the prefix is bound.

you can make jlibs generate, the expected output.
the QName of rootElement is given no prefix. so it used no prefix.

if you change:

```java
QName rootElement = new QName("http://w3shcools.com", "Author");
```

to

```java
QName rootElement = new QName("http://w3shcools.com", "Author", "w3c");
```

then jlibs will generate your expected output.

**Comment by brendonstephens93** [comment]
Thanks Santhosh. Do you know if there is a way to retrieve the namespace prefix from the xsd file? If I reference ```xsModel.getNamespaces().item(0)``` it seems to only return the namespace, what I would be after is both the namespace and the prefix associated with it.

**Comment by santhosh-tekuri** [comment]
you can get prefix as shown below:

```java
String xsdFile = ...
XSModel xsModel = ...
XMLDocument xml = ....
XSUtil.suggestNamespacePrefixes(URLUtil.toURL(xsdFile), xml);
String namespace = "http://w3shcools.com";
String prefix = xml.getNamespaceSupport().findPrefix(namespace);
if(prefix==null)
    prefix = "";
QName rootElement = new QName(namespace, "Author", prefix);
new XSInstance().generate(...);
```

**Comment by brendonstephens93** [comment]
```
XSModel xsModel = new XSParser().parse(xsdFile.getAbsolutePath());
		
StringWriter sampleXml = new StringWriter();

XMLDocument xml = new XMLDocument(new StreamResult(sampleXml), false, 4, null);
		
// suggest namespace prefixes so they don't default to ns1, ns2 etc
XSUtil.suggestNamespacePrefixes(URLUtil.toURL(xsdFile.getAbsolutePath()), xml);
		
ArrayList<String> prefixList = Collections.list(xml.getNamespaceSupport().getDeclaredPrefixes());

System.out.println("Prefix Array: " + prefixList);
```

Hi Santhosh. 

When I run the above code, I always get this output:

```Prefix Array: [xml]```

I am expecting to see the defined prefixes however they are never populated into the MyNamespaceSupport object.

**Comment by santhosh-tekuri** [comment]
```java
XSUtil.suggestNamespacePrefixes(URLUtil.toURL(xsdFile.getAbsolutePath()), xml);
```

the above line does not add any prefixes. it just adds them to the suggestions list
when you declare any uri, from suguestion list, it uses the suggested prefix
