### ISSUE TITLE
Question: When do you want to release?

### ISSUE THREAD

**Issue by PiQ99** [santhosh-tekuri/jlibs#61]
Hey,

it's me again. First thank you for your quick "fix" with the defaultElements. Actually I just wanted to ask, when do you want to release approximately a new version of jlibs ?

Thanks in advance for your answer.

**Comment by santhosh-tekuri** [comment]
2.2 version is release

https://repo1.maven.org/maven2/in/jlibs/jlibs-xsd/2.2/
