### ISSUE TITLE
Generating XML from XSD 1.1 Schema

### ISSUE THREAD

**Issue by pderoxas** [santhosh-tekuri/jlibs#65]
I am getting an error related to a XSD 1.1 _**openContent**_ feature when generating XML from schema. Is there a way to configure the library to enable XSD 1.1?

The error is as follows:
```
[Error] navigation.xsd:90:43: s4s-elt-invalid-content.1: The content of 'navigation-model' is invalid.  Element 'openContent' is invalid, misplaced, or occurs too often.
```

Below is a the snippet from my schema that is causing the error. 
```
<xs:openContent mode="interleave">
    <xs:any namespace="http://www.xyz.com/SOA/myapp/2 http://www.xyz.com/SOA/preview/2" processContents="strict"/>
</xs:openContent>
```

**Comment by santhosh-tekuri** [comment]
JLibs uses xerces 2.11.0 library to parse xml schema. This library does not yet support XSD 1.1

but xerces 2.11.0 beta library has experimental support for some of XSD 1.1 features which includes openContent.

you can download it from [here](http://www.eu.apache.org/dist//xerces/j/source/Xerces-J-tools.2.11.0-xml-schema-1.1-beta.zip)

remove xerces 2.11.0 jars from classpath and add xerces 2.11.0 beta jars to class path and try to generate sample xml. This might work.

**Comment by pderoxas** [comment]
Thank you for your suggestion. I was able to download the xerces 2.11.0-beta source and build the jar locally. Unfortunately, it is still throwing that error. I will step through the xerces code and see if I can implement a fix or workaround. Thanks for your time!

**Comment by pderoxas** [comment]
Update: I was able to enable XSD 1.1 by adding the following line in XSParser.java at around line 60:

```
config.setParameter(Constants.XERCES_PROPERTY_PREFIX + "validation/schema/version", "http://www.w3.org/XML/XMLSchema/v1.1".intern());
```

I'm now able to successfully generate xml from an XSD 1.1 schema!

**Comment by santhosh-tekuri** [comment]
thanks for the update. 
I added XSParser.enableSchema11() method

closing the issue...

**Comment by pderoxas** [comment]
Great, thanks! Any timeline on when you'll release this latest version to MVN Central? Thanks again!!

**Comment by santhosh-tekuri** [comment]
version 2.2.1 is now available in mvn central;

**Comment by pderoxas** [comment]
Thanks! You the man!
