### ISSUE TITLE
Values generated for the <any> element not valid

### ISSUE THREAD

**Issue by IsraSmida** [santhosh-tekuri/jlibs#67]
`cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'ns:anyElement'.`

**Comment by santhosh-tekuri** [comment]
please provider xml schema to reproduce the issue

**Comment by IsraSmida** [comment]
`<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Quote" type="QuoteType" />
	<xs:element name="Order" type="OrderType" />
	<xs:complexType name="QuoteType">
		<xs:sequence>
			<xs:element name="Line" type="ProdType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderType">
		<xs:sequence>
			<xs:element name="Line" type="OrderLineType" maxOccurs=" unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ProdType">
		<xs:sequence>
			<xs:element name="Desc" type="xs:string" />
			<xs:element name="Price" type="xs:double" />
			<xs:any minOccurs="0" maxOccurs="unbounded"/> 
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderLineType">
		<xs:sequence>
			<xs:element name="Product" type="ProdType" />
			<xs:element name="Qty" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>
`

Thank you !

**Comment by santhosh-tekuri** [comment]
fixed with commit 34faee2e6d9d17e3738efc73f7d3a7c33167a570

**Comment by santhosh-tekuri** [comment]
fix is available in 2.2.2-SNAPSHOT from maven repo: https://oss.sonatype.org/content/repositories/snapshots/
