### ISSUE TITLE
keeps generating optional elements even with 'instance.generateOptionalElements = false;'

### ISSUE THREAD

**Issue by IsraSmida** [santhosh-tekuri/jlibs#68]

**Comment by santhosh-tekuri** [comment]
please provide xsd file to reproduce

**Comment by IsraSmida** [comment]
`<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Quote">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Line" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Desc" type="xs:string" />
							<xs:element name="Price" type="xs:double" minOccurs="0" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Line" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Product">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Desc" type="xs:string" />
										<xs:element name="Price" type="xs:double" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Qty" type="xs:int" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
`

**Comment by santhosh-tekuri** [comment]
I do not see any optional element in your schema.

<xs:element name="Price" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>

is not optional element. if minOccurs=0 and maxOccurs=1 then we treat it as optional Element

**Comment by IsraSmida** [comment]
Ok I see. Thank you.
