### ISSUE TITLE
From XSD to XML Generation

### ISSUE THREAD

**Issue by m-jndl** [santhosh-tekuri/jlibs#70]
Hi Santhosh,

Hope you are doing well.
I came across your wiki: 
https://github.com/santhosh-tekuri/jlibs/wiki/XSInstance.

I have the same logic in java, but getting error "Exception in thread "main" java.lang.NoSuchMethodError: org.apache.xerces.xs.XSObjectList.isEmpty()Z
    at jlibs.xml.xsd.XSInstance$XSSampleVisitor$1.preProcess(XSInstance.java:265)
    at jlibs.xml.xsd.XSInstance$XSSampleVisitor$1.preProcess(XSInstance.java:238)
    at jlibs.core.graph.WalkerUtil.walk(WalkerUtil.java:41)
    at jlibs.xml.xsd.XSInstance.generate(XSInstance.java:126)
    at jlibs.xml.xsd.XSInstance.generate(XSInstance.java:93)
    at com.xsdtoxml.XMLGen.main(XMLGen.java:68)
"

I am using the below java file
package com.xsdtoxml;

import java.io.File;

import javax.xml.namespace.QName;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.stream.StreamResult;

import org.apache.xerces.xs.XSModel;
import org.apache.xerces.xs.XSNamespaceItem;
import org.apache.xerces.xs.XSObject;

import jlibs.xml.sax.XMLDocument;
import jlibs.xml.xsd.XSInstance;
import jlibs.xml.xsd.XSParser;

/**
- 
- @author leijiang
- @param arg0
-            : source xsd location
- @param arg1
-            : destination xml location
- @param arg2
-            : root name
- @param arg3
- ```
         : target namespace (if empty string is passed in, convert to null)
  ```
  
  */
  public class XMLGen {
  public static void main(String[] args) {
      File xsd = new File("src/demoXSD.xsd");
      XSInstance xsi = new XSInstance();
      xsi.generateOptionalAttributes = true;
      xsi.generateOptionalElements = true;
      xsi.generateFixedAttributes = true;
      xsi.generateDefaultAttributes = true;
      xsi.generateAllChoices=true;
  
  ```
  // args[3] = args[3].equalsIgnoreCase("") ? null : "";
  QName root = new QName("", "PurchaseOrder");
  
  XSModel xsmodel = new XSParser().parse(xsd.getAbsolutePath());
  xsmodel.getNamespaceItems();
  XMLDocument sampleXml;
  for (int i = 0; i <= xsmodel.getNamespaceItems().getLength(); i++) {
      XSNamespaceItem one = xsmodel.getNamespaceItems().item(i);
      // XSNamedMap map=xsmodel.getComponents();
  
      XSObject onject = xsmodel.getAnnotations().item(i);
  
      // System.out.println(one.getSchemaNamespace());
      // System.out.println(onject.getNamespaceItem());
  
      // System.out.println(onject.getName());
      // System.out.println(onject.getNamespace());
      // System.out.println(onject.getClass());
      // System.out.println(onject.getType());
  }
  try {
  
      sampleXml = new XMLDocument(new StreamResult("src/demoXSD.xml"), false, 4, null);
      // System.out.println(xsmodel.getAnnotations().getLength());
  
      xsi.generate(xsmodel, root, sampleXml);
  
  } catch (TransformerConfigurationException e) {
      e.printStackTrace();
  }
  
  System.out.println("Sample xml has been generated");
  ```
  
  }

}

Could you please help me with the issue, am unable to debug why XSObjectList is coming empty.
Thanks & Regards,
Megha

**Comment by santhosh-tekuri** [comment]
check that you are using xercesImpl-2.11.0.jar in classpath
