### ISSUE TITLE
Problem parsing xsd with 2 import for same namespace

### ISSUE THREAD

**Issue by clauspbeck** [santhosh-tekuri/jlibs#72]
Hello,

thanks for jlibs, it's a nice lib and normally do as predicted.

I have some problems at the moment since our xsd contains 2 import with the same namspace

eg.
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:oio:fnyf:hentoversigtdata:1.0.0"
  xmlns:fnyf="urn:oio:fnyf:hentoversigtdata:1.0.0"
  xmlns:fnyf1="urn:oio:fnyf:1.0.0"
  elementFormDefault="qualified"
  xml:lang="DA">
  <xsd:import namespace="urn:oio:fnyf:1.0.0" schemaLocation="RUTIdentifikatorSamling.xsd"/>
  <xsd:import namespace="urn:oio:fnyf:1.0.0" schemaLocation="SprogKode.xsd"/>
  <xsd:element name="HentOversigtsData" type="fnyf:HentOversigtsDataType"/>
  <xsd:complexType name="HentOversigtsDataType">
    <xsd:sequence>
      <xsd:element ref="fnyf1:SprogKode"/>
      <xsd:element ref="fnyf:RUTIdentifikatorSamling"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

which result in 
Error] HentOversigtsData.xsd:13:42: src-resolve: Cannot resolve the name 'fnyf1:SprogKode' to a(n) 'element declaration' component.
[Error] HentOversigtsData.xsd:13:42: src-resolve: Cannot resolve the name 'fnyf1:SprogKode' to a(n) 'element declaration' component.

-----

It seems there should be a oppurtunity to set this feature for the SAXParser (http://apache.org/xml/features/honour-all-schemaLocations, true), i found something in a old thread, but i can't see if it possible to set this feature.
[Xceres same namespace](https://xerces.apache.org/xerces2-j/features.html)

Is it possible ocould there be another solution?

All the best
Claus

**Comment by santhosh-tekuri** [comment]
use `XSModel.honourAllSchemaLocations()` flag to enable this feature, as below:

```java
XSParser xsParser = new XSParser();
xsParser.honourAllSchemaLocations();
XSModel xsModel = xsParser.parse("/Users/santhosh/temp/multi_import.xsd");
```
