### ISSUE TITLE
Stream parsing

### ISSUE THREAD

**Issue by oleg-smith** [santhosh-tekuri/jlibs#77]
Now is is only possible to attach a listener and execute some code within it.
Is it possible to provide an iterator instead, that will take next node on `hasNext` call?

**Comment by santhosh-tekuri** [comment]
i do not understand the context of the question. please elaborate

**Comment by oleg-smith** [comment]
for example:
```
dog.addXPath(xpath);
Iterator<NodeItem> iterator = dog.sniff(); // here it is lazily evaluating input stream as client code calls iterator.hasNext/next
```

**Comment by santhosh-tekuri** [comment]
XMLDog is implemented based on SAX, which is push based.
returning iterator as in your example, is pull based. so this is not possible with xmldog.

**Comment by oleg-smith** [comment]
Push can be easily converted to pull, if you emit a node, and then suspend, remembering context.

**Comment by santhosh-tekuri** [comment]
suspending involves more than one thread. and this drops performance significantly.

also unlike traditional xpath engines, xmldog evaluates all xpaths parallely in one parse.

**Comment by oleg-smith** [comment]
I’not talking about using another thread for suspending. It can be easily done just with control flags.

**Comment by santhosh-tekuri** [comment]
I do not think, it can be achieved with control flags.

I may be wrong or do not know what you mean control flags. can you please demonstrate it with simple program:

Write a SAX implementation which prints employee names from employees.xml file. In SAX implementation the amount of time taken to print first 10 employees is always same, irrespective of number of employees in employees.xml. i,e. if xml file contains 1 million employees or 1000 employees, the time taken to print first 10 employee names will be same.

now modify this implementation to return iterator of employee names(should still use SAX). NOTE this implementation should still take same time to print first 10 employees from xml file, irrespective of number of employees.
