### ISSUE TITLE
How to Connect to a auth token enabled remote Https link of XSD to generate XML / Crawl

### ISSUE THREAD

**Issue by abhijeetmalik** [santhosh-tekuri/jlibs#78]
I have a link which requires authentication using auth token. I managed to connect to the link by passing the auth token as part of the URL instead of in header parameters. 
But the XSD has multiple sub parts at the same URL path location. When I pass this URL to the XSParser for generating the model, it doesn't crawl to generate the model for all sub structures. Only opens the top level object. 

String xsdFile = <https URI with ?access_token=XXX in the end>

			XSParser xsp = new XSParser();
			XSModel xsModel = xsp.parse(xsdFile);

This eventually when used to generate the sample , fails to create complete schema payload & only creates top level object sample. 

File f = <local output file>
			QName rootElement = new QName(nameSpace, rootElemetName);

			XSInstance xsInstance = new XSInstance();
			xsInstance.loadOptions(options);

			XMLDocument sampleXml = new XMLDocument(new StreamResult(f), true, 4, null);
			xsInstance.generate(xsModel, rootElement, sampleXml);
			generatedXML = IOUtils.toString(f.toURI(), StandardCharsets.UTF_8);

When I try to use the jlibs crawler to crawl the whole XSD locally, it failed with the standard error java.io.IOException: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException 
 lineNumber: 1; columnNumber: 1; "Content is not allowed in prolog" . But i checked the URL independently from a browser, and the generated file does have a valid XML tag as the first object, absence of which usually tends to be the cause of this error. 

Can you please suggest a way to generate sample from the payload , or how to crawl the URL ? 

Thanks,
Abhi

**Comment by santhosh-tekuri** [comment]
`XSParser` is a simple wrapper around xerces API for loading xml schema.

```java
public XSParser(LSResourceResolver entityResolver, DOMErrorHandler errorHandler)
```

use the above constructor, pass your own implementation of `LSResourceResolver`.
in your `LSResourceResolver` implementation, you read the schema from uri passing authtoken and return `LSInput` with the schema string
