### ISSUE TITLE
The offset and raw text information of match results is not available

### ISSUE THREAD

**Issue by P403n1x87** [santhosh-tekuri/jlibs#80]
Would it be possible to extend the result object to include the offset with respect to the beginning of the input stream where the match has occurred? Optionally, I would find useful having the raw text content available (i.e. any escaped text, e.g. "J&amp;D").

**Comment by santhosh-tekuri** [comment]
i dont get the context. which result object ??

please tell me which part in jlibs you are talking about

**Comment by P403n1x87** [comment]
Ah sorry, my apologies. I'm referring to XMLDog. It would be great to have the position of each matching result, so that whenever one needs to replace a value, the initial offset is already known.

**Comment by santhosh-tekuri** [comment]
[wont fix]
it is not easy to provide position. none of the xpath parsers provide such information.
even sax parsers does not provide position information for attributes.
