### ISSUE TITLE
Parsing XML file with XMLDOG with xmlns attribute in the root element

### ISSUE THREAD

**Issue by nazrul074** [santhosh-tekuri/jlibs#81]
Hi Santhosh,
I am using your XMLDOG library. It is great for large XML file parsing with very low memory footprint. However, I am facing an issue when XML root node has an attribute of xmlns="http://www.teaaaaaaa.xx/elrs/ACMP" if I remove this attribute from the root node then it successfully process the file. How to ignore this attribute?

Sample XML:
`<EXTRACT xmlns="http://www.teaaaaaaa.xx/elrs/ACMP"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.teaaaaaaa.ca/elrs/ACMP polarisall.xsd" 
 BatchIdentifier="XXXXXXXXXXXXXX" NumberOfFilesInDelivery="1" FileSequenceNumber="1" >
 <instrument>
        <registrationTime>0831</registrationTime>
    </instrument>
</EXTRACT>`

sample code (in Groovy ):
` DefaultNamespaceContext nsContext = new DefaultNamespaceContext()
        boolean useSTAX = false
        XMLDog dog = new XMLDog(nsContext)
        dog.addXPath("/EXTRACT/instrument")
        Event event = dog.createEvent()
        event.setXMLBuilder(new DOMBuilder())
        event.setListener(new InstantEvaluationListener() {
            @Override
            public void onNodeHit(Expression expression, NodeItem nodeItem) {
                org.w3c.dom.Node node = (org.w3c.dom.Node) nodeItem.xml
                StringWriter writer = new StringWriter();
                Transformer transformer = TransformerFactory.newInstance().newTransformer();
                transformer.transform(new DOMSource(node), new StreamResult(writer));
                JSONObject instrument = org.json.XML.toJSONObject(writer.toString(), true).getJSONObject("instrument")
            }
            @Override
            public void finishedNodeSet(Expression expression) {
                log.debug("Finished Nodeset: " + expression.getXPath());
            }
            @Override
            public void onResult(Expression expression, Object result) {
                // this method is called only for xpaths which returns primitive result
                // i.e result will be one of String, Boolean, Double
                log.debug("XPath: " + expression.getXPath() + " result: " + result);
            }
        })
        dog.sniff(event, new InputSource(inputStream), useSTAX)`

Thanks

**Comment by nazrul074** [comment]
Hi I found the solution. I was using xpath expression "/EXTRACT/instrument" which search only default namespace. I have changed the expression to *[local-name()='InstrumentList']/*[local-name()='instrument'].
it is working now.

**Comment by oleg-smith** [comment]
@santhosh-tekuri @nazrul074 Could you propose a way to skip `xmlns` while parsing completely? For example, for arbitrary xpath expression

**Comment by santhosh-tekuri** [comment]
you better use [XSLT](https://www.w3schools.com/xml/xsl_intro.asp) to do any transformations to the xml and then feed the modified xml to xmldog
