### ISSUE TITLE
Parsing your purchaseOrder.xsd

### ISSUE THREAD

**Issue by PiQ99** [santhosh-tekuri/jlibs#84]
Hey,
I have a problem while parsing a xsd-file containing a "abstract"-Attribute set to true. It seems to be a dead-lock in the class XSUtil.java and the method "getSubTypes(..,..)" 
You already provided an example XSD file for this handling under "master/xsd/xsds/purchaseOrder.xsd". If I select this file and want to generate an example XML file based on the element "PurchaseOrder" but it loops infinitely.

Best regards

**Comment by santhosh-tekuri** [comment]
I am unable to reproduce this.

make sure you are using [version 2.2.2](https://mvnrepository.com/artifact/in.jlibs/jlibs-xsd/2.2.2)
there are some changes to getSubTypes in version 2.2.2
seems those changes have fixed it. commit 3dc2b700a

**Comment by PiQ99** [comment]
Thanks for your really fast reply! I will try it again, tomorrow!

**Comment by santhosh-tekuri** [comment]
not reproducible with 2.2.2
