### ISSUE TITLE
On I18N, how to choose the Location other than the default?

### ISSUE THREAD

**Issue by cvgaviao** [santhosh-tekuri/jlibs#87]
For example, in a stateless web app I would need to  obtain the user locale from the request and then obtain the right resource bundle.

**Comment by santhosh-tekuri** [comment]
you can get user locale from http request header [Accept-Language](https://www.w3.org/International/questions/qa-accept-lang-locales.en)

for example, if you are using java servlets they provide method [ServletRequest.getLocale()](https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getLocale%28%29)

currently I18N class, has no methods to fetch messages for specific locale. I am adding them. 
temporarly you can just copy those added methods put it in some util class and use it.

**Comment by santhosh-tekuri** [comment]
check the new method in commit b4fe670
