### ISSUE TITLE
XML can't be generated

### ISSUE THREAD

**Issue by gantzerjulien** [santhosh-tekuri/jlibs#96]
I tried to generate a xml sample from the linked xsd but i got an error (java.lang.StringIndexOutOfBoundsException: begin 0, end 4, length 2)

[cbpr.zip](https://github.com/santhosh-tekuri/jlibs/files/6574343/cbpr.zip)

Here is my code : 

`XSModel xsModel = (new XSParser()).parse(xsdPath);
        XSInstance instance = new XSInstance();
        instance.minimumElementsGenerated = 1;
        instance.maximumElementsGenerated = 2;
        instance.minimumListItemsGenerated = 1;
        instance.maximumListItemsGenerated = 2;
        instance.generateDefaultAttributes = true;
        instance.generateOptionalAttributes = true;
        instance.maximumRecursionDepth = 1;
        instance.generateAllChoices = true;
        instance.showContentModel = false;
        instance.generateOptionalElements = true;
        QName rootElement = new QName(targetNamespace, "Document");
        XMLDocument sampleXml = new XMLDocument(new StreamResult(xmlPath), true, 4, (String)null);
        instance.generate(xsModel, rootElement, sampleXml);`

I think the problem come from an optional recursive tag (include in himself). When i set instance.generateOptionalElements to false the generation work.

Have you got an idea where the problem come from ?

**Comment by santhosh-tekuri** [comment]
the fix is available in version 3.0.1

i just uploaded 3.0.1 version.
it may take few hours, to get it synched to maven central repository
