### ISSUE TITLE
The constraint sequence from the xsd is not respected

### ISSUE THREAD

**Issue by gantzerjulien** [santhosh-tekuri/jlibs#97]
I generate an xml sample from an xsd with <sequence> tags but in the in the generated xml the order is not respected every time. When i launch multiple times my code i get different results like it is random. I use the last version (3,0,1). Here is my code 

`    private void createXml(Document doc, String xsdPath, String xmlPath) throws TransformerConfigurationException {
        Element rootElem = doc.getDocumentElement();
        String targetNamespace = null;
        if (rootElem != null && rootElem.getNodeName().equals("xs:schema")) {
            targetNamespace = rootElem.getAttribute("targetNamespace");
        }

        XSModel xsModel = (new XSParser()).parse(xsdPath);
        XSInstance instance = new XSInstance();
        instance.minimumElementsGenerated = 1;
        instance.maximumElementsGenerated = 2;
        instance.minimumListItemsGenerated = 1;
        instance.maximumListItemsGenerated = 2;
        instance.generateDefaultAttributes = true;
        instance.generateOptionalAttributes = true;
        instance.maximumRecursionDepth = 5;
        instance.generateAllChoices = true;
        instance.showContentModel = false;
        instance.generateOptionalElements = true;
        QName rootElement = new QName(targetNamespace, "Document");
        XMLDocument sampleXml = new XMLDocument(new StreamResult(xmlPath), false, 4, (String)null);
        instance.generate(xsModel, rootElement, sampleXml);
    }`

I also join the concerned xsd and with an exemple of generated sample (a bit modified)
[CBPR_pacs_008_001_08_enriched-model.zip](https://github.com/santhosh-tekuri/jlibs/files/6717435/CBPR_pacs_008_001_08_enriched-model.zip)

**Comment by santhosh-tekuri** [comment]
i am not sure what do you mean by `xsd with tags`. give me small xsd sample, with generated output and expected output

**Comment by gantzerjulien** [comment]
Sorry i meant "with tags sequence" which are supposed to guarantee the order of the included tags.
By creating a small example, I found the problem. I generate all tags presents in the choice tag xsd and those are in random order. 
For me this is not an issue anymore so i close this

Thanks for the reactivity anyway
